src/Main/ArticleBundle/Entity/Article.php
<?php

namespace Main\ArticleBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Main\AbstractBundle\Model\UploadFileMover;
use Main\AbstractBundle\Entity\Language;


/**
 * Article
 *
 * @ORM\Table(name="articles", indexes={@ORM\Index(name="article_language", columns={"language_id"})})
 * @ORM\Entity
 */
class Article
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=225, nullable=false)
     * @Assert\NotBlank()
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(name="content", type="text", nullable=false)
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @var string
     *
     * @ORM\Column(name="image", type="string", length=225, nullable=true)
     * @Assert\File(
     *     maxSize = "600000000",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    private $image;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime", nullable=true)
     */
    private $created;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated", type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @var \Main\AbstractBundle\Entity\Language
     *
     * @ORM\ManyToOne(targetEntity="Main\AbstractBundle\Entity\Language")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="language_id", referencedColumnName="id")
     * })
     * @Assert\NotBlank()
     */
    private $language;

    /**
     * @var string
     *
     * @ORM\Column(name="path", type="string", length=225, nullable=true)
     */
    private $path;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Article
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set image
     *
     * @param string $image
     * @return Article
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return string 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Article
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Article
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set language
     *
     * @param \Main\AbstractBundle\Entity\Language $language
     * @return Article
     */
    public function setLanguage(Language $language = null)
    {
        $this->language = $language;

        return $this;
    }

    /**
     * Get language
     *
     * @return \Main\AbstractBundle\Entity\Language
     */
    public function getLanguage()
    {
        return $this->language;
    }
    
    public function getAbsolutePath()
    {
        return (null === $this->path)? null: $this->getUploadRootDir().'/'.$this->path;
    }

    public function getWebPath()
    {
        return (null === $this->path)? null: $this->getUploadDir(). $this->path;
    }

    protected function getUploadRootDir()
    {
        // the absolute directory path where uploaded articles should be saved
        return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    protected function getUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/articles';
    }
    
    public function processFile()
    {
        if (! ($this->image instanceof UploadedFile) ) {
            return false;
        }
        $oldPath = $this->getWebPath();
        
        $uploadFileMover = new UploadFileMover();
        $this->path = $uploadFileMover->moveUploadedFile($this->image, self::getUploadDir());
        
        if($oldPath && null != $oldPath && $oldPath != $this->path) {
            if(file_exists($oldPath)) {
                unlink($oldPath);
            }
        }
    }
    
    public function getSmallContent() {
        return substr($this->content, 0, 100) . ' ...';
    }

}

src/Main/ArticleBundle/Form/ArticleType.php
<?php

namespace Main\ArticleBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ArticleType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('image', 'file', array(
                'data_class' => null,
                'required' => false
            ))
            ->add('language', 'entity', array(
                'class' => 'MainAbstractBundle:Language',
                'property' => 'language'
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Main\ArticleBundle\Entity\Article'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'main_articlebundle_article';
    }
}

src/Main/ArticleBundle/Controller/ArticleController.php
<?php

namespace Main\ArticleBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Main\ArticleBundle\Entity\Article;
use Main\ArticleBundle\Form\ArticleType;

/**
 * Article controller.
 *
 * @Route("/articles")
 */
class ArticleController extends Controller
{

    /**
     * Lists all Article entities.
     *
     * @Route("/", name="articles")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('MainArticleBundle:Article')->findAll();

        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Article entity.
     *
     * @Route("/", name="articles_create")
     * @Method("POST")
     * @Template("MainArticleBundle:Article:new.html.twig")
     */
    public function createAction(Request $request)
    {
        $entity = new Article();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $entity->processFile();
            $entity->setCreated(new \DateTime());
            $em = $this->getDoctrine()->getManager();
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('articles'));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Article entity.
     *
     * @param Article $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Article $entity)
    {
        $form = $this->createForm(new ArticleType(), $entity, array(
            'action' => $this->generateUrl('articles_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Article entity.
     *
     * @Route("/new", name="articles_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Article();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Article entity.
     *
     * @Route("/{id}", name="articles_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MainArticleBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Article entity.
     *
     * @Route("/{id}/edit", name="articles_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MainArticleBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Article entity.
    *
    * @param Article $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Article $entity)
    {
        $form = $this->createForm(new ArticleType(), $entity, array(
            'action' => $this->generateUrl('articles_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Article entity.
     *
     * @Route("/{id}", name="articles_update")
     * @Method("PUT")
     * @Template("MainArticleBundle:Article:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('MainArticleBundle:Article')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Article entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $entity->setUpdated(new \DateTime());
            
            $entity->processFile();
            $em->flush();

            return $this->redirect($this->generateUrl('articles'));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Article entity.
     *
     * @Route("/{id}", name="articles_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('MainArticleBundle:Article')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Article entity.');
            }

            if(null != $entity->getWebPath()) {
                unlink($entity->getWebPath());
            }
            
            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('articles'));
    }

    /**
     * Creates a form to delete a Article entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('articles_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
}

src/Main/ArticleBundle/Resources/views/Article/edit.html.twig
{% extends "MainAbstractBundle::layout.html.twig" %}

{% block stylesheets %}  
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/mainabstract/css/colorbox.css') }}">
{% endblock %}

{% block container %}
    {{ parent() }}
    <div class="container">
        
        <h2 class="text-center">Article Edit</h2>
        <p class="text-center" style="margin:30px 0;">{{ form_errors(edit_form) }}</p>
        <div id="form">
            {{ form_start(edit_form, {'attr': { 'id': 'contact', 'class': 'clearfix'} }) }}
            
                {{ form_row(edit_form._token) }}
                <div class="col-md-6 col-lg-12 form-group">
                    <div class="error">{{ form_errors(edit_form.title) }}</div>
                    {{ form_widget(edit_form.title, { 'type': 'text', 'attr': {'placeholder': 'Title', 'class': 'form-control', 'id': 'title'} }) }}
                </div>
                <div class="col-md-6 col-lg-12 form-group">
                    <div class="error">{{ form_errors(edit_form.content) }}</div>
                    {{ form_widget(edit_form.content, { 'type': 'email', 'attr': {'placeholder': 'Content', 'class': 'form-control', 'id': 'content', 'rows': '8'} }) }}
                </div>
                <div class="col-md-6 col-lg-6 form-group">
                    <div class="error">{{ form_errors(edit_form.image) }}</div>
                    {{ form_widget(edit_form.image, { 'attr': {'class': 'dropdown-menu', 'role': 'menu', 'accept': "image/*"} }) }}
                </div>
                <div class="col-md-6 col-lg-6 form-group">
                    <div class="error">{{ form_errors(edit_form.language) }}</div>
                    {{ form_widget(edit_form.language, {  'attr': {'class': 'select-list'} }) }}
                </div>
                <div class="col-md-12">
                    <button id="submit" type="submit" class="col-md-12 col-sm-12 col-xs-12 blue-btn">Update</button>
                </div>

            <!--contact-form--> 
        </div>
        <a href="{{ path('articles') }}">Back to the list</a>
        
    </div>
{% endblock %}

{% block homeSlider %}{% endblock %}
{% block single_item %}{% endblock %}
{% block projects %}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/mainabstract/js/tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        tinymce.init({
            selector: "#main_articlebundle_article_content",
            theme: "modern",
                plugins: [
                     "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                     "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                     "save table contextmenu directionality emoticons template paste textcolor"
               ],
               content_css: "css/content.css",
               toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor", 
               style_formats: [
                    {title: 'Bold text', inline: 'b'},
                    {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                    {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                    {title: 'Example 1', inline: 'span', classes: 'example1'},
                    {title: 'Example 2', inline: 'span', classes: 'example2'},
                    {title: 'Table styles'},
                    {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
                ],
                
        });
        
        $(document.body).on('click', '.dropdown-menu li', function(event) {
            var $target = $(event.currentTarget);
            $target.closest('.btn-group')
                .find('[data-bind="label"]').text($target.text())
                .end()
                .children('.dropdown-toggle').dropdown('toggle');
            
            return false;
        });
    </script>
{% endblock %}

src/Main/ArticleBundle/Resources/views/Article/index.html.twig
{% extends "MainAbstractBundle::layout.html.twig" %}

{% block stylesheets %}
    {{ parent() }}
    <link href="{{ asset('bundles/mainabstract/css/colorbox.css') }}" media="all" rel="stylesheet" type="text/css">
{% endblock %}

{% block container %}
    {{ parent() }}
    <div class="container">
        <h2 class="text-center">{{'Article list'|trans}}</h2>
        <div id="form">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th class="text-center no-head">Id</th>
                    <th class="middle">Title</th>
                    <th class="middle">Content</th>
                    <th class="middle">Image</th>
                    <th class="middle">Language</th>
                    <th class="middle">Created</th>
                    <th class="middle">Updated</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for entity in entities %}
                    <tr>
                        <th scope="row" width="10%" class="text-center no"><a href="{{ path('articles_show', { 'id': entity.id }) }}">{{ entity.id }}</a</th>
                        <td class="middle">{{ entity.title }}</td>
                        <td class="middle">{{ entity.content|raw }}</td>
                        <td class="middle">
                            {% if entity.webPath is not null %}
                                <img class="col-md-12" src="{{ asset(entity.webPath) }}" alt="{{ entity.image }}" />
                            {% endif %}
                        </td>
                        <td class="middle">{{ entity.language.language }}</td>
                        <td class="middle">{% if entity.created %}{{ entity.created|date('Y-m-d H:i:s') }}{% endif %}</td>
                        <td>{% if entity.updated %}{{ entity.updated|date('Y-m-d H:i:s') }}{% endif %}</td>
                        <td>
                            <a href="{{ path('articles_show', { 'id': entity.id }) }}">show</a>
                            <br/>
                            <a href="{{ path('articles_edit', { 'id': entity.id }) }}">edit</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <a class="blue-btn text-center button btn-block" href="{{ path('articles_new') }}">{{'Create a new entry'|trans}}</a>
</div>

{% endblock %}
{% block homeSlider %}{% endblock %}
{% block single_item %}{% endblock %}
{% block projects %}{% endblock %}

src/Main/ArticleBundle/Resources/views/Article/new.html.twig
{% extends "MainAbstractBundle::layout.html.twig" %}

{% block stylesheets %}  
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/mainabstract/css/colorbox.css') }}">
{% endblock %}

{% block container %}
    {{ parent() }}
    <div class="container">
        
        <h2 class="text-center">Article creation</h2>
        <p class="text-center" style="margin:30px 0;">{{ form_errors(form) }}</p>
        <div id="form">
        
            {{ form_start(form, {'attr': { 'id': 'contact', 'class': 'clearfix', 'novalidate': ''} }) }}
                {{ form_row(form._token) }}
                <div class="col-md-6 col-lg-12 form-group">
                    <div class="error">{{ form_errors(form.title) }}</div>
                    {{ form_widget(form.title, { 'type': 'text', 'attr': {'placeholder': 'Title', 'class': 'form-control', 'id': 'title'} }) }}
                </div>
                <div class="col-md-6 col-lg-12 form-group">
                    <div class="error">{{ form_errors(form.content) }}</div>
                    {{ form_widget(form.content, { 'attr': {'placeholder': 'Content', 'class': 'form-control', 'id': 'content', 'rows': '8'} }) }}
                </div>
                <div class="col-md-6 col-lg-6 form-group">
                    <div class="error">{{ form_errors(form.image) }}</div>
                    {{ form_widget(form.image, { 'attr': {'class': 'dropdown-menu', 'role': 'menu', 'accept': "image/*"} }) }}
                </div>
                <div class="col-md-6 col-lg-6 form-group">
                    <div class="error">{{ form_errors(form.language) }}</div>
                    {{ form_widget(form.language, {  'attr': {'class': 'select-list'} }) }}
                </div>
                <br/>
                <div class="col-md-12">
                    <button id="submit" type="submit" class="col-md-12 col-sm-12 col-xs-12 blue-btn">Create</button>
                </div>

            <!--contact-form--> 
        </div>
        <a href="{{ path('articles') }}">Back to the list</a>
    </div>
{% endblock %}

{% block homeSlider %}
<ul>
<li style="text-align: left;">
<span style="color: #ff0000;">this is new article
</span>
</li>
</ul>
{% endblock %}
{% block single_item %}{% endblock %}
{% block projects %}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('bundles/mainabstract/js/tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript">
        $( document ).ready(function() {
            tinymce.init({
                selector: "#main_articlebundle_article_content",
                theme: "modern",
                plugins: [
                     "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
                     "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
                     "save table contextmenu directionality emoticons template paste textcolor"
               ],
               toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
               style_formats: [
                    {title: 'Bold text', inline: 'b'},
                    {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
                    {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
                    {title: 'Example 1', inline: 'span', classes: 'example1'},
                    {title: 'Example 2', inline: 'span', classes: 'example2'},
                    {title: 'Table styles'},
                    {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
                ],
                autofocus: "#main_articlebundle_article_content"
            });
        });

        $(document.body).on('click', '.dropdown-menu li', function(event) {
            var $target = $(event.currentTarget);
            $target.closest('.btn-group')
                .find('[data-bind="label"]').text($target.text())
                .end()
                .children('.dropdown-toggle').dropdown('toggle');
            
            return false;
        });
    </script>
{% endblock %}

src/Main/ArticleBundle/Resources/views/Article/show.html.twig
{% extends "MainAbstractBundle::layout.html.twig" %}

{% block container %}
    
    {{ parent() }}
    <div class="container">
    <h1>Article</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ entity.title }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ entity.content|raw }}</td>
            </tr>
            {% if entity.webPath is not null %}
                <tr>
                    <th>Image</th>
                    <td><img src="{{ asset(entity.webPath) }}" alt="{{ entity.image }}" /></td>
                </tr>
            {% endif %}
            <tr>
                <th>Language</th>
                <td>{{ entity.language.language }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ entity.created|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Updated</th>
                <td>{{ entity.updated|date('Y-m-d H:i:s') }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('articles') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('articles_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
    </div>
{% endblock %}

{% block homeSlider %}{% endblock %}
{% block single_item %}{% endblock %}
{% block projects %}{% endblock %}